.ubuntu_common: &ubuntuCommon
  image: ubuntu:latest
  before_script:
    - apt-get update -qy
    - apt-get install -y git python3-dev python3-pip

test:ubuntu_TFlatest_python3.5:
  <<: *ubuntuCommon
  script:
  - pip3 install .
  - python3 setup.py test

.arch_common: &archCommon
  before_script:
  - pacman -S --noconfirm python python-pip git base-devel

test:arch_TFlatest_python3.6:
  image: pritunl/archlinux:2017-05-13
  <<: *archCommon
  script:
  - pip install .
  - python setup.py test
