build: false

environment:
  matrix:



    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.1"
      PYTHON_ARCH: "64"


init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

test_script:
  - "%PYTHON%\\python.exe setup.py test"