version: 2

references:

  ubuntu_deps: &ubuntu_deps
    run:
      name: Install dependencies on Ubuntu.
      command: |
        apt-get update -qy
        apt-get install -y git python3-dev python3-pip curl

  arch_deps: &arch_deps
    run:
      name: Install dependencies on Arch Linux.
      command: |
        pacman -S --noconfirm python python-pip git base-devel curl

  install: &install
    run:
      name: Install.
      command: |
        pip3 install .

  test: &test
    run:
      name: Run tests.
      command: |
        python3 setup.py test

  deploy: &deploy
    run:
      name: PyPI deploy
      command: |
        pip3 install wheel setuptools --upgrade
        bash <(curl -fsSL https://raw.githubusercontent.com/Cognexa/ci-utils/master/pypi_deploy.sh)

  add_rw_key: &add_rw_key
    add_ssh_keys:
      fingerprints:
        - "c2:d9:82:5d:1b:09:11:3f:4f:cd:30:82:28:1e:ce:96"

  doc: &doc
    run:
      name: Generate documentation
      command: |
        bash <(curl -fsSL https://raw.githubusercontent.com/Cognexa/ci-utils/master/doc_deploy.sh)

jobs:

  test_ubuntu_latest:
    docker:
      - image: ubuntu:latest
    working_directory: ~/cxflow
    steps:
      - *ubuntu_deps
      - checkout
      - *install
      - *test

  test_ubuntu_rolling:
    docker:
      - image: ubuntu:rolling
    working_directory: ~/cxflow
    steps:
      - *ubuntu_deps
      - checkout
      - *install
      - *test

  test_archlinux:
    docker:
      - image: pritunl/archlinux:2017-07-08
    working_directory: ~/cxflow
    steps:
      - *arch_deps
      - checkout
      - *install
      - *test

  generate_documentation:
    docker:
      - image: ubuntu:rolling
    working_directory: ~/cxflow
    steps:
      - *ubuntu_deps
      - checkout
      - *install
      - *add_rw_key
      - *doc

  deploy:
    docker:
      - image: pritunl/archlinux:2017-07-08
    working_directory: ~/cxflow
    steps:
      - *arch_deps
      - checkout
      - *deploy

workflows:

  version: 2
  test-doc-deploy:
    jobs:
      - test_ubuntu_latest
      - test_ubuntu_rolling
      - test_archlinux
      - generate_documentation:
          filters:
            branches:
              only: master
          requires:
            - test_ubuntu_latest
            - test_ubuntu_rolling
            - test_archlinux
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - test_ubuntu_latest
            - test_ubuntu_rolling
            - test_archlinux
            - generate_documentation
